### ISSUE TITLE
where is objectnav/modular_objectnav_hm3d.yaml?

### ISSUE THREAD

**Issue by JiahuaPei** [facebookresearch/home-robot#531]

**Comment by JiahuaPei** [comment]
just use this
```

habitat:
  seed: 42 

  simulator:
    type: "Sim-v0"
    forward_step_size: 0.25
    turn_angle: 30
    create_renderer: False
    requires_textures: True
    auto_sleep: False
    step_physics: True
    concur_render: False
    needs_markers: True
    update_articulated_agent: True

    scene_dataset: './hm3d/mp3d.scene_dataset_config.json'
    additional_object_paths: []
    default_agent_id: 0
    
    debug_render: False
    debug_render_articulated_agent: False
    kinematic_mode: False
    should_setup_semantic_ids: True
    debug_render_goal: True
    robot_joint_start_noise: 0.0
    ctrl_freq: 120.0
    ac_freq_ratio: 4
    load_objs: True
    hold_thresh: 0.15
    grasp_impulse: 10000.0
    agents:
      main_agent:
        height: 0.88
        radius: 0.18
        max_climb: 0.2
        max_slope: 45.0
        grasp_managers: 1
        sim_sensors:
          rgb_sensor:
            type: "HabitatSimRGBSensor"
            height: 480
            width: 640
            position: [0.0, 0.88, 0.0]
            orientation: [0.0, 0.0, 0.0]
            hfov: 79
            sensor_subtype: "PINHOLE"
            noise_model: "None"
            noise_model_kwargs: {}
          depth_sensor:
            type: "HabitatSimDepthSensor"
            height: 480
            width: 640
            position: [0.0, 0.88, 0.0]
            orientation: [0.0, 0.0, 0.0]
            hfov: 79
            sensor_subtype: "PINHOLE"
            noise_model: "None"
            noise_model_kwargs: {}
            min_depth: 0.5
            max_depth: 5.0
            normalize_depth: true
          semantic_sensor:
            type: "HabitatSimSemanticSensor"
            height: 480
            width: 640
            position: [0.0, 0.88, 0.0]
            orientation: [0.0, 0.0, 0.0]
            hfov: 79
            sensor_subtype: "PINHOLE"
      
        is_set_start_state: False
        joint_start_noise: 0.1
        
    agents_order: ['main_agent']
    default_agent_navmesh: True
    navmesh_include_static_objects: False
   
    habitat_sim_v0:
      
      gpu_gpu: False
      allow_sliding: True
      frustum_culling: True
      enable_physics: False
      enable_hbao: False
      physics_config_file: './data/default.physics_config.json'
      leave_context_with_background_renderer: False
      enable_gfx_replay_save: False
    ep_info: None
    object_ids_start: 100
    renderer:
      enable: false 
      gpu_device_id: 0 
      enable_batch_renderer: False
      composite_files: None
      classic_replay_renderer: False
   


  task:
    type: ObjectNav-v1
    physics_target_sps: 60.0
    actions: # 使用小写键名
      stop:
        type: StopAction
      move_forward:
        type: MoveForwardAction
        tilt_angle: 15
      turn_left:
        type: TurnLeftAction
        tilt_angle: 15
      turn_right:
        type: TurnRightAction
        tilt_angle: 15
      look_up:
        type: LookUpAction
        tilt_angle: 30
      look_down:
        type: LookDownAction
        tilt_angle: 30

    goal_sensor_uuid: objectgoal_sensor 

    lab_sensors:
      objectgoal_sensor:
        type: ObjectGoalSensor
        goal_spec: "TASK_CATEGORY_ID"
        goal_spec_max_val: 6 
      compass_sensor: 
        type: CompassSensor
      gps_sensor: 
        type: GPSSensor
        dimensionality: 2

    measurements: 
      distance_to_goal:
        type: DistanceToGoal
        distance_to: VIEW_POINTS
      success:
        type: Success
        success_distance: 1.0
      spl:
        type: SPL
      soft_spl:
        type: SoftSPL
      distance_to_goal_reward:
        type: DistanceToGoalReward
      top_down_map:
        type: TopDownMap
        max_episode_steps: 1000
        map_padding: 3
        map_resolution: 1024
        draw_source: True
        draw_border: True
        draw_shortest_path: False
        draw_view_points: True
        draw_goal_positions: True
        draw_goal_aabbs: True
        fog_of_war:
          draw: True
          visibility_dist: 5.0
          fov: 79
      collisions:
        type: Collisions


    reward_measure: distance_to_goal_reward
    success_measure: spl
    success_reward: 2.5
    slack_reward: -0.01
    end_on_success: True
    rank0_env0_measure_names: ['habitat_perf']
    rank0_measure_names: []
    count_obj_collisions: True
    settle_steps: 5
    constraint_violation_ends_episode: True
    constraint_violation_drops_object: False
    force_regenerate: False
    should_save_to_cache: False
    object_in_hand_sample_prob: 0.167
    min_start_distance: 3.0
    render_target: True
    filter_colliding_states: True
    num_spawn_attempts: 200
    spawn_max_dist_to_obj: 2.0
    base_angle_noise: 0.523599
    spawn_max_dist_to_obj_delta: 0.02
    recep_place_shrink_factor: 0.8
    ee_sample_factor: 0.2
    ee_exclude_region: 0.0
    base_noise: 0.05
    spawn_region_scale: 0.2
    joint_max_impulse: -1.0
    desired_resting_position: [0.5, 0.0, 1.0]
    use_marker_t: True
    cache_robot_init: False
    success_state: 0.0
    should_enforce_target_within_reach: False
    task_spec_base_path: habitat/task/rearrange/pddl/
    task_spec: ''
    pddl_domain_def: replica_cad
    obj_succ_thresh: 0.3
    enable_safe_drop: False
    art_succ_thresh: 0.15
    robot_at_thresh: 2.0
    min_distance_start_agents: -1.0


  dataset:
    type: ObjectNav-v1
    split: val
    data_path: "./hm3d/task_datasets/objectnav_hm3d_v2/val/val.json.gz" 
    scenes_dir: "./hm3d/" 
    content_scenes: ["*"]

 
  environment:
    max_episode_steps: 500
    max_episode_seconds: 10000000
    iterator_options:
      cycle: True
      shuffle: True
      group_by_scene: True
      num_episode_sample: 500
      max_scene_repeat_episodes: -1
      max_scene_repeat_steps: 10000
      step_repetition_range: 0.2
```
